apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: mysql
  type: external

resources:
- external-service.yaml

secretGenerator:
- name: mysql-credentials
  literals:
  - username=root
  - password=root
  - database=wordpress
  - host=192.168.103.250
