apiVersion: v1
kind: Service
metadata:
  name: nacos-external
  labels:
    app: nacos
    type: external
spec:
  type: ExternalName
  externalName: placeholder.nacos.com
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nacos-external
subsets:
- addresses:
  - ip: 192.168.1.102
  ports:
  - port: 8848
