apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: redis
  type: external

resources:
- external-service.yaml

secretGenerator:
- name: redis-credentials
  literals:
  - host=placeholder
  - port=6379
  - password=placeholder
