apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  WP_DEBUG: "true"
  WP_DEBUG_LOG: "/var/www/html/wp-content/debug.log"
  WP_DEBUG_DISPLAY: "true"
  NACOS_CONFIG_ADDR: "nacos-pre.internal.com:8848"
